// Finance vertical seed data (e.g., credit.ai)
export const companies = [
  // Disruptors/Fintech
  {
    company_name: 'Brex',
    slug: 'brex',
    description: 'AI-powered corporate credit cards and spend management platform. Fastest growing fintech in enterprise.',
    website: 'https://brex.com',
    categories: JSON.stringify(['Credit Cards', 'Banking', 'AI/ML']),
    company_type: 'disruptor',
    key_stat: '$12B+ Valuation',
    founded: '2017',
    hq_location: 'San Francisco, CA',
    employees: '1500+',
    featured: 1,
  },
  {
    company_name: 'Ramp',
    slug: 'ramp',
    description: 'AI-first corporate card and expense management. Automated savings, real-time spend insights.',
    website: 'https://ramp.com',
    categories: JSON.stringify(['Credit Cards', 'AI/ML']),
    company_type: 'disruptor',
    key_stat: '$7.65B Valuation',
    founded: '2019',
    hq_location: 'New York, NY',
    employees: '800+',
    featured: 1,
  },
  {
    company_name: 'Credit Karma',
    slug: 'credit-karma',
    description: 'AI-powered credit score monitoring and financial recommendations. Acquired by Intuit.',
    website: 'https://creditkarma.com',
    categories: JSON.stringify(['Credit Scoring', 'AI/ML']),
    company_type: 'disruptor',
    key_stat: '$8.1B Acquisition',
    founded: '2007',
    hq_location: 'Oakland, CA',
    employees: '1500+',
    featured: 1,
  },
  {
    company_name: 'Upstart',
    slug: 'upstart',
    description: 'AI lending platform using ML for credit decisions beyond FICO. Personal loans, auto, HELOC.',
    website: 'https://upstart.com',
    categories: JSON.stringify(['Lending', 'AI/ML', 'Credit Scoring']),
    company_type: 'disruptor',
    key_stat: '2M+ Loans Originated',
    founded: '2012',
    hq_location: 'San Mateo, CA',
    employees: '1600+',
    featured: 0,
  },
  {
    company_name: 'Chime',
    slug: 'chime',
    description: 'AI-driven digital banking with credit builder card. 22M+ customers, no-fee banking.',
    website: 'https://chime.com',
    categories: JSON.stringify(['Banking', 'Credit Cards']),
    company_type: 'disruptor',
    key_stat: '22M+ Customers',
    founded: '2012',
    hq_location: 'San Francisco, CA',
    employees: '2000+',
    featured: 0,
  },
  {
    company_name: 'Klarna',
    slug: 'klarna',
    description: 'AI-powered BNPL and payments. AI customer service handles 66% of support inquiries.',
    website: 'https://klarna.com',
    categories: JSON.stringify(['BNPL', 'Payments', 'AI/ML']),
    company_type: 'disruptor',
    key_stat: '$6.7B Valuation',
    founded: '2005',
    hq_location: 'Stockholm, Sweden',
    employees: '5000+',
    featured: 0,
  },
  {
    company_name: 'Plaid',
    slug: 'plaid',
    description: 'Financial data infrastructure. API connecting fintech apps to bank accounts. Powers 8000+ apps.',
    website: 'https://plaid.com',
    categories: JSON.stringify(['Banking', 'Fraud Detection']),
    company_type: 'disruptor',
    key_stat: '8000+ Apps Connected',
    founded: '2013',
    hq_location: 'San Francisco, CA',
    employees: '1800+',
    featured: 0,
  },
  // Legacy Banks
  {
    company_name: 'JPMorgan Chase',
    slug: 'jpmorgan',
    description: 'Largest US bank. Chase credit cards, AI-powered fraud detection, digital banking innovation.',
    website: 'https://jpmorganchase.com',
    categories: JSON.stringify(['Banking', 'Credit Cards', 'AI/ML']),
    company_type: 'incumbent',
    key_stat: '$4T+ Assets',
    founded: '2000',
    hq_location: 'New York, NY',
    employees: '290000+',
    featured: 1,
  },
  {
    company_name: 'Capital One',
    slug: 'capital-one',
    description: '"What\'s in your wallet?" AI-first bank with major ML investment. Consumer credit leader.',
    website: 'https://capitalone.com',
    categories: JSON.stringify(['Banking', 'Credit Cards', 'AI/ML']),
    company_type: 'incumbent',
    key_stat: 'AI-First Bank',
    founded: '1994',
    hq_location: 'McLean, VA',
    employees: '55000+',
    featured: 0,
  },
  {
    company_name: 'American Express',
    slug: 'amex',
    description: 'Premium credit cards with AI customer service and fraud prevention. 130M+ cardholders.',
    website: 'https://americanexpress.com',
    categories: JSON.stringify(['Credit Cards', 'Fraud Detection']),
    company_type: 'incumbent',
    key_stat: '130M+ Cardholders',
    founded: '1850',
    hq_location: 'New York, NY',
    employees: '75000+',
    featured: 0,
  },
  {
    company_name: 'Visa',
    slug: 'visa',
    description: 'Payment network processing 65,000+ transactions per second. AI fraud detection at scale.',
    website: 'https://visa.com',
    categories: JSON.stringify(['Payments', 'Fraud Detection', 'AI/ML']),
    company_type: 'incumbent',
    key_stat: '65K TPS',
    founded: '1958',
    hq_location: 'San Francisco, CA',
    employees: '26000+',
    featured: 0,
  },
  {
    company_name: 'Experian',
    slug: 'experian',
    description: 'Credit bureau with AI-powered credit scoring and identity verification solutions.',
    website: 'https://experian.com',
    categories: JSON.stringify(['Credit Scoring', 'Fraud Detection']),
    company_type: 'incumbent',
    key_stat: '1.4B Consumer Files',
    founded: '1996',
    hq_location: 'Dublin, Ireland',
    employees: '22000+',
    featured: 0,
  },
]

export const subdomains = [
  // Company subdomains
  { subdomain: 'chase', type: 'company', status: 'available' },
  { subdomain: 'amex', type: 'company', status: 'available' },
  { subdomain: 'capitalone', type: 'company', status: 'available' },
  { subdomain: 'discover', type: 'company', status: 'available' },
  { subdomain: 'brex', type: 'company', status: 'claimed', owner_name: 'Brex' },
  { subdomain: 'ramp', type: 'company', status: 'claimed', owner_name: 'Ramp' },
  { subdomain: 'klarna', type: 'company', status: 'available' },
  { subdomain: 'affirm', type: 'company', status: 'available' },
  // Agent identities
  { subdomain: 'fico', type: 'agent', status: 'available', agent_name: 'FICO', agent_description: 'Credit scoring AI agent' },
  { subdomain: 'vantage', type: 'agent', status: 'available', agent_name: 'VantageScore', agent_description: 'Alternative credit scoring' },
  { subdomain: 'erica', type: 'agent', status: 'claimed', agent_name: 'Erica', agent_description: 'Bank of America AI assistant', owner_name: 'Bank of America' },
  { subdomain: 'eno', type: 'agent', status: 'claimed', agent_name: 'Eno', agent_description: 'Capital One AI assistant', owner_name: 'Capital One' },
  // Category subdomains
  { subdomain: 'rewards', type: 'category', status: 'available' },
  { subdomain: 'business', type: 'category', status: 'available' },
  { subdomain: 'cashback', type: 'category', status: 'available' },
  { subdomain: 'travel', type: 'category', status: 'available' },
  { subdomain: 'secured', type: 'category', status: 'available' },
  { subdomain: 'api', type: 'reserved', status: 'reserved' },
]

export const articles = [
  {
    title: 'Capital One Completes $35B Discover Acquisition',
    excerpt: 'Deal reshapes credit card market, creates fifth-largest credit card issuer in US.',
    category: 'Market',
    published_at: new Date().toISOString(),
  },
  {
    title: 'Chase Sapphire Launches AI-Powered Rewards Optimization',
    excerpt: 'New feature uses ML to maximize point earnings based on spending patterns.',
    category: 'Product',
    published_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    title: 'Brex Reaches $12B Valuation with Enterprise Expansion',
    excerpt: 'AI corporate cards gain traction as companies automate expense management.',
    category: 'Funding',
    published_at: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    title: 'Fed Report: AI Credit Scoring Outperforms FICO',
    excerpt: 'Study shows ML models approve 40M more thin-file consumers with same default rates.',
    category: 'Research',
    published_at: new Date(Date.now() - 259200000).toISOString(),
  },
  {
    title: 'Klarna AI Agent Handles 66% of Support Inquiries',
    excerpt: 'BNPL giant reduces customer service costs while improving satisfaction scores.',
    category: 'Technology',
    published_at: new Date(Date.now() - 345600000).toISOString(),
  },
]

export const outbound = [
  { company: 'JPMorgan Chase', contact_name: 'Jamie Dimon', title: 'CEO', priority: 'high', status: 'sent' },
  { company: 'Capital One', contact_name: 'Richard Fairbank', title: 'CEO', priority: 'high', status: 'sent' },
  { company: 'Brex', contact_name: 'Pedro Franceschi', title: 'CEO', priority: 'high', status: 'sent' },
  { company: 'Visa', contact_name: 'Ryan McInerney', title: 'CEO', priority: 'medium', status: 'sent' },
  { company: 'Experian', contact_name: 'Brian Cassin', title: 'CEO', priority: 'medium', status: 'sent' },
]
