// Internet.com demo seed data — tight, focused, 6 companies max

export const companies = [
  {
    company_name: 'Google',
    slug: 'google',
    description: 'The world\'s dominant search engine. Google IS the internet for billions.',
    website: 'https://google.com',
    categories: JSON.stringify(['Search', 'Cloud', 'AI']),
    company_type: 'platform',
    key_stat: '$307B Revenue',
    founded: '1998',
    hq_location: 'Mountain View, CA',
    employees: '182000+',
    featured: 1,
  },
  {
    company_name: 'Cloudflare',
    slug: 'cloudflare',
    description: 'Powers and protects 20% of all websites. The infrastructure layer of the internet.',
    website: 'https://cloudflare.com',
    categories: JSON.stringify(['Cloud', 'Security', 'Domains']),
    company_type: 'infrastructure',
    key_stat: '20% of Web Traffic',
    founded: '2009',
    hq_location: 'San Francisco, CA',
    employees: '4000+',
    featured: 1,
  },
  {
    company_name: 'OpenAI',
    slug: 'openai',
    description: 'Creator of ChatGPT. Redefining how people use the internet.',
    website: 'https://openai.com',
    categories: JSON.stringify(['AI', 'Search']),
    company_type: 'disruptor',
    key_stat: '$300B Valuation',
    founded: '2015',
    hq_location: 'San Francisco, CA',
    employees: '3000+',
    featured: 1,
  },
  {
    company_name: 'Verisign',
    slug: 'verisign',
    description: 'Operates the .com registry. Every .com domain resolves through Verisign.',
    website: 'https://verisign.com',
    categories: JSON.stringify(['Domains', 'Security']),
    company_type: 'infrastructure',
    key_stat: '.COM Registry',
    founded: '1995',
    hq_location: 'Reston, VA',
    employees: '900+',
    featured: 1,
  },
  {
    company_name: 'Amazon Web Services',
    slug: 'aws',
    description: 'The cloud that runs the internet. 32% market share.',
    website: 'https://aws.amazon.com',
    categories: JSON.stringify(['Cloud', 'AI']),
    company_type: 'platform',
    key_stat: '32% Cloud Share',
    founded: '2006',
    hq_location: 'Seattle, WA',
    employees: '100000+',
    featured: 1,
  },
  {
    company_name: 'Meta',
    slug: 'meta',
    description: 'Facebook, Instagram, WhatsApp. 4 billion monthly users.',
    website: 'https://meta.com',
    categories: JSON.stringify(['Social', 'AI']),
    company_type: 'platform',
    key_stat: '4B Monthly Users',
    founded: '2004',
    hq_location: 'Menlo Park, CA',
    employees: '67000+',
    featured: 1,
  },
]

export const subdomains = [
  // Company names — BIN pressure generators
  { subdomain: 'google', type: 'company', status: 'available', display_name: 'Google', description: 'The world\'s search engine' },
  { subdomain: 'cloudflare', type: 'company', status: 'available', display_name: 'Cloudflare', description: 'Internet infrastructure' },
  { subdomain: 'openai', type: 'company', status: 'available', display_name: 'OpenAI', description: 'AI research lab' },
  { subdomain: 'aws', type: 'company', status: 'available', display_name: 'AWS', description: 'Cloud computing' },
  { subdomain: 'meta', type: 'company', status: 'available', display_name: 'Meta', description: 'Social platforms' },
  { subdomain: 'stripe', type: 'company', status: 'available', display_name: 'Stripe', description: 'Payments infrastructure' },
  // Category keywords — premium namespace
  { subdomain: 'search', type: 'category', status: 'available', display_name: 'Search', description: 'Search engine namespace' },
  { subdomain: 'ai', type: 'category', status: 'available', display_name: 'AI', description: 'Artificial intelligence' },
  { subdomain: 'cloud', type: 'category', status: 'available', display_name: 'Cloud', description: 'Cloud computing' },
  { subdomain: 'security', type: 'category', status: 'available', display_name: 'Security', description: 'Cybersecurity' },
  { subdomain: 'mail', type: 'category', status: 'available', display_name: 'Mail', description: 'Email services' },
  { subdomain: 'news', type: 'category', status: 'available', display_name: 'News', description: 'Internet news' },
  { subdomain: 'dns', type: 'category', status: 'available', display_name: 'DNS', description: 'Domain name system' },
  { subdomain: 'domains', type: 'category', status: 'available', display_name: 'Domains', description: 'Domain industry' },
]

// No articles or outbound for this demo
export const articles = []
export const outbound = []
