// Internet.com vertical seed data
export const companies = [
  // Platform Giants — who SHOULD own internet.com
  {
    company_name: 'Google / Alphabet',
    slug: 'google',
    description: 'The world\'s dominant search engine and internet platform. Search, Chrome, Android, YouTube, Cloud — Google IS the internet for billions of people.',
    website: 'https://google.com',
    categories: JSON.stringify(['Search & Discovery', 'Cloud & Infrastructure', 'AI & Machine Learning', 'Advertising & Media']),
    company_type: 'platform',
    key_stat: '$307B Revenue',
    founded: '1998',
    hq_location: 'Mountain View, CA',
    employees: '182000+',
    featured: 1,
  },
  {
    company_name: 'Cloudflare',
    slug: 'cloudflare',
    description: 'Powers and protects ~20% of all websites. CDN, DDoS protection, DNS, Workers — the infrastructure layer of the modern internet.',
    website: 'https://cloudflare.com',
    categories: JSON.stringify(['Cloud & Infrastructure', 'Cybersecurity', 'Domain & DNS']),
    company_type: 'infrastructure',
    key_stat: '~20% of Web Traffic',
    founded: '2009',
    hq_location: 'San Francisco, CA',
    employees: '4000+',
    featured: 1,
  },
  {
    company_name: 'OpenAI',
    slug: 'openai',
    description: 'Creator of ChatGPT and GPT-4. Redefining how humans interact with the internet through conversational AI.',
    website: 'https://openai.com',
    categories: JSON.stringify(['AI & Machine Learning', 'Search & Discovery']),
    company_type: 'disruptor',
    key_stat: '$300B Valuation',
    founded: '2015',
    hq_location: 'San Francisco, CA',
    employees: '3000+',
    featured: 1,
  },
  {
    company_name: 'Verisign',
    slug: 'verisign',
    description: 'Operates the .com and .net registries — the backbone of internet naming. Every .com domain resolves through Verisign infrastructure.',
    website: 'https://verisign.com',
    categories: JSON.stringify(['Domain & DNS', 'Cybersecurity']),
    company_type: 'infrastructure',
    key_stat: '.COM Registry Operator',
    founded: '1995',
    hq_location: 'Reston, VA',
    employees: '900+',
    featured: 1,
  },
  {
    company_name: 'Amazon Web Services',
    slug: 'aws',
    description: 'The cloud that runs the internet. 32% market share. Route 53, CloudFront, S3 — AWS hosts more of the web than anyone.',
    website: 'https://aws.amazon.com',
    categories: JSON.stringify(['Cloud & Infrastructure', 'AI & Machine Learning']),
    company_type: 'platform',
    key_stat: '32% Cloud Market Share',
    founded: '2006',
    hq_location: 'Seattle, WA',
    employees: '100000+',
    featured: 0,
  },
  {
    company_name: 'Meta',
    slug: 'meta',
    description: 'Facebook, Instagram, WhatsApp, Threads. 3.98B monthly active users — the social layer of the internet.',
    website: 'https://meta.com',
    categories: JSON.stringify(['Social & Communication', 'AI & Machine Learning', 'Advertising & Media']),
    company_type: 'platform',
    key_stat: '3.98B Monthly Users',
    founded: '2004',
    hq_location: 'Menlo Park, CA',
    employees: '67000+',
    featured: 0,
  },
  {
    company_name: 'Anthropic',
    slug: 'anthropic',
    description: 'Creator of Claude. Building safe, beneficial AI that is reshaping internet search, coding, and knowledge work.',
    website: 'https://anthropic.com',
    categories: JSON.stringify(['AI & Machine Learning']),
    company_type: 'disruptor',
    key_stat: '$60B Valuation',
    founded: '2021',
    hq_location: 'San Francisco, CA',
    employees: '1500+',
    featured: 0,
  },
  {
    company_name: 'GoDaddy',
    slug: 'godaddy',
    description: 'World\'s largest domain registrar. 84M+ domains under management. The front door for small business on the internet.',
    website: 'https://godaddy.com',
    categories: JSON.stringify(['Domain & DNS', 'E-Commerce']),
    company_type: 'platform',
    key_stat: '84M+ Domains',
    founded: '1997',
    hq_location: 'Tempe, AZ',
    employees: '7000+',
    featured: 0,
  },
  {
    company_name: 'Akamai',
    slug: 'akamai',
    description: 'Pioneer CDN serving 30% of global web traffic. Edge computing, security, and content delivery at massive scale.',
    website: 'https://akamai.com',
    categories: JSON.stringify(['Cloud & Infrastructure', 'Cybersecurity']),
    company_type: 'infrastructure',
    key_stat: '30% of Web Traffic',
    founded: '1998',
    hq_location: 'Cambridge, MA',
    employees: '10000+',
    featured: 0,
  },
  {
    company_name: 'Perplexity',
    slug: 'perplexity',
    description: 'AI-powered answer engine replacing traditional search. The future of how people find information on the internet.',
    website: 'https://perplexity.ai',
    categories: JSON.stringify(['AI & Machine Learning', 'Search & Discovery']),
    company_type: 'disruptor',
    key_stat: '$9B Valuation',
    founded: '2022',
    hq_location: 'San Francisco, CA',
    employees: '300+',
    featured: 0,
  },
  {
    company_name: 'ICANN',
    slug: 'icann',
    description: 'Internet Corporation for Assigned Names and Numbers. Governs the global domain name system and internet naming policy.',
    website: 'https://icann.org',
    categories: JSON.stringify(['Domain & DNS']),
    company_type: 'infrastructure',
    key_stat: 'DNS Governance',
    founded: '1998',
    hq_location: 'Los Angeles, CA',
    employees: '400+',
    featured: 0,
  },
  {
    company_name: 'Stripe',
    slug: 'stripe',
    description: 'The payments infrastructure of the internet. Powers transactions for millions of businesses worldwide.',
    website: 'https://stripe.com',
    categories: JSON.stringify(['Payments & Fintech', 'Developer Tools']),
    company_type: 'platform',
    key_stat: '$91B Valuation',
    founded: '2010',
    hq_location: 'San Francisco, CA',
    employees: '8000+',
    featured: 0,
  },
]

export const subdomains = [
  // Platform giants
  { subdomain: 'google', type: 'company', status: 'available', display_name: 'Google', description: 'The world\'s dominant search engine' },
  { subdomain: 'cloudflare', type: 'company', status: 'available', display_name: 'Cloudflare', description: 'Infrastructure layer of the modern internet' },
  { subdomain: 'openai', type: 'company', status: 'available', display_name: 'OpenAI', description: 'Creator of ChatGPT and GPT-4' },
  { subdomain: 'aws', type: 'company', status: 'available', display_name: 'AWS', description: 'The cloud that runs the internet' },
  { subdomain: 'meta', type: 'company', status: 'available', display_name: 'Meta', description: 'The social layer of the internet' },
  { subdomain: 'anthropic', type: 'company', status: 'available', display_name: 'Anthropic', description: 'Creator of Claude AI' },
  { subdomain: 'stripe', type: 'company', status: 'available', display_name: 'Stripe', description: 'Payments infrastructure of the internet' },
  { subdomain: 'verisign', type: 'company', status: 'available', display_name: 'Verisign', description: '.COM registry operator' },
  { subdomain: 'godaddy', type: 'company', status: 'available', display_name: 'GoDaddy', description: 'World\'s largest domain registrar' },
  { subdomain: 'perplexity', type: 'company', status: 'available', display_name: 'Perplexity', description: 'AI-powered answer engine' },
  // Category subdomains — these are the premium namespace plays
  { subdomain: 'search', type: 'category', status: 'available', display_name: 'Search', description: 'The search engine namespace' },
  { subdomain: 'ai', type: 'category', status: 'available', display_name: 'AI', description: 'Artificial intelligence hub' },
  { subdomain: 'cloud', type: 'category', status: 'available', display_name: 'Cloud', description: 'Cloud computing namespace' },
  { subdomain: 'security', type: 'category', status: 'available', display_name: 'Security', description: 'Cybersecurity hub' },
  { subdomain: 'dns', type: 'category', status: 'available', display_name: 'DNS', description: 'Domain name system namespace' },
  { subdomain: 'domains', type: 'category', status: 'available', display_name: 'Domains', description: 'Domain industry hub' },
  { subdomain: 'payments', type: 'category', status: 'available', display_name: 'Payments', description: 'Payment systems namespace' },
  { subdomain: 'social', type: 'category', status: 'available', display_name: 'Social', description: 'Social media namespace' },
  { subdomain: 'mail', type: 'category', status: 'available', display_name: 'Mail', description: 'Email services hub' },
  { subdomain: 'news', type: 'category', status: 'available', display_name: 'News', description: 'Internet news namespace' },
  // Agent identities — the agentic web layer
  { subdomain: 'api', type: 'agent', status: 'available', display_name: 'API Gateway', description: 'Universal internet API endpoint', agent_name: 'API Gateway', agent_description: 'Universal internet API endpoint' },
  { subdomain: 'agent', type: 'agent', status: 'available', display_name: 'Agent Hub', description: 'Agentic web identity resolver', agent_name: 'Agent Hub', agent_description: 'Agentic web identity resolver' },
  { subdomain: 'llm', type: 'agent', status: 'available', display_name: 'LLM Router', description: 'AI model routing and inference', agent_name: 'LLM Router', agent_description: 'AI model routing and inference' },
  { subdomain: 'docs', type: 'reserved', status: 'reserved', display_name: 'Docs', description: 'Documentation portal' },
]

export const articles = [
  {
    title: 'Internet.com: From 1992 Pioneer to Web3 Namespace',
    excerpt: 'One of the original internet domains is entering its next era — as a multi-layer revenue asset through domain tokenization.',
    category: 'Feature',
    published_at: new Date().toISOString(),
  },
  {
    title: 'The Domain Monetization Crisis: After AFD, What\'s Next?',
    excerpt: 'Google AFD is dead. Parking revenue is collapsing. DS3 offers a new path: subdomains, fractions, and directories.',
    category: 'Analysis',
    published_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    title: 'Why AI Companies Are the Natural Buyers for Category-Defining .COMs',
    excerpt: 'As AI reshapes the internet, the domains that define categories are more valuable than ever.',
    category: 'Market',
    published_at: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    title: 'Fractional Domain Ownership: How DOMA Tokenizes Premium Names',
    excerpt: 'Sell up to 49%, keep DNS control, maintain your high BIN. The new playbook for premium domain monetization.',
    category: 'Product',
    published_at: new Date(Date.now() - 259200000).toISOString(),
  },
  {
    title: '1 Billion Requests: Inside Internet.com\'s Traffic Machine',
    excerpt: 'With 8,500+ daily uniques and massive global reach, internet.com\'s type-in traffic alone is a monetizable asset.',
    category: 'Data',
    published_at: new Date(Date.now() - 345600000).toISOString(),
  },
]

export const outbound = [
  { company: 'Google', contact_name: 'Sundar Pichai', title: 'CEO', priority: 'high', status: 'pending' },
  { company: 'Cloudflare', contact_name: 'Matthew Prince', title: 'CEO', priority: 'high', status: 'pending' },
  { company: 'OpenAI', contact_name: 'Sam Altman', title: 'CEO', priority: 'high', status: 'pending' },
  { company: 'Verisign', contact_name: 'Jim Bidzos', title: 'CEO', priority: 'high', status: 'pending' },
  { company: 'GoDaddy', contact_name: 'Aman Bhutani', title: 'CEO', priority: 'medium', status: 'pending' },
  { company: 'Anthropic', contact_name: 'Dario Amodei', title: 'CEO', priority: 'medium', status: 'pending' },
  { company: 'Perplexity', contact_name: 'Aravind Srinivas', title: 'CEO', priority: 'medium', status: 'pending' },
]
