// Legal vertical seed data (e.g., legal.ai)
export const companies = [
  // Disruptors
  {
    company_name: 'Harvey AI',
    slug: 'harvey',
    description: 'GPT-powered legal AI assistant. Contract analysis, legal research, document drafting for law firms.',
    website: 'https://harvey.ai',
    categories: JSON.stringify(['Contract Analysis', 'Legal Research', 'Document Drafting']),
    company_type: 'disruptor',
    key_stat: '$650M+ Funding',
    founded: '2022',
    hq_location: 'San Francisco, CA',
    employees: '150+',
    featured: 1,
  },
  {
    company_name: 'Casetext / CoCounsel',
    slug: 'casetext',
    description: 'AI legal research platform. Acquired by Thomson Reuters. CoCounsel powers AI-assisted research.',
    website: 'https://casetext.com',
    categories: JSON.stringify(['Legal Research', 'AI/ML']),
    company_type: 'disruptor',
    key_stat: 'TR Acquired',
    founded: '2013',
    hq_location: 'San Francisco, CA',
    employees: '200+',
    featured: 1,
  },
  {
    company_name: 'Ironclad',
    slug: 'ironclad',
    description: 'AI contract lifecycle management. Digital contracting platform for legal and business teams.',
    website: 'https://ironcladapp.com',
    categories: JSON.stringify(['Contract Analysis', 'Corporate']),
    company_type: 'disruptor',
    key_stat: '$3.2B Valuation',
    founded: '2014',
    hq_location: 'San Francisco, CA',
    employees: '700+',
    featured: 1,
  },
  {
    company_name: 'Luminance',
    slug: 'luminance',
    description: 'AI-powered contract review for M&A due diligence, lease review, and compliance.',
    website: 'https://luminance.com',
    categories: JSON.stringify(['Contract Analysis', 'eDiscovery', 'Compliance']),
    company_type: 'disruptor',
    key_stat: '700+ Customers',
    founded: '2015',
    hq_location: 'London, UK',
    employees: '250+',
    featured: 0,
  },
  {
    company_name: 'EvenUp',
    slug: 'evenup',
    description: 'AI for personal injury demand letters. Generates comprehensive settlement demands from case files.',
    website: 'https://evenuplaw.com',
    categories: JSON.stringify(['Litigation', 'Document Drafting']),
    company_type: 'disruptor',
    key_stat: '$135M Funding',
    founded: '2019',
    hq_location: 'San Francisco, CA',
    employees: '300+',
    featured: 0,
  },
  {
    company_name: 'Everlaw',
    slug: 'everlaw',
    description: 'AI-powered ediscovery and litigation platform. Cloud-native, built for complex litigation.',
    website: 'https://everlaw.com',
    categories: JSON.stringify(['eDiscovery', 'Litigation']),
    company_type: 'disruptor',
    key_stat: '$2B Valuation',
    founded: '2010',
    hq_location: 'Oakland, CA',
    employees: '500+',
    featured: 0,
  },
  // Incumbents
  {
    company_name: 'Westlaw / Thomson Reuters',
    slug: 'westlaw',
    description: 'Dominant legal research platform. AI integration via CoCounsel acquisition.',
    website: 'https://legal.thomsonreuters.com',
    categories: JSON.stringify(['Legal Research', 'AI/ML']),
    company_type: 'incumbent',
    key_stat: 'Market Leader',
    founded: '1975',
    hq_location: 'Toronto, Canada',
    employees: '25000+',
    featured: 1,
  },
  {
    company_name: 'LexisNexis',
    slug: 'lexisnexis',
    description: 'Legal data, analytics, and AI-powered research. Part of RELX Group.',
    website: 'https://lexisnexis.com',
    categories: JSON.stringify(['Legal Research', 'AI/ML']),
    company_type: 'incumbent',
    key_stat: '3M+ Legal Docs',
    founded: '1970',
    hq_location: 'New York, NY',
    employees: '11000+',
    featured: 0,
  },
  {
    company_name: 'Litera',
    slug: 'litera',
    description: 'Legal document management and AI drafting tools. Powers AmLaw 100 firms.',
    website: 'https://litera.com',
    categories: JSON.stringify(['Document Drafting', 'Corporate']),
    company_type: 'incumbent',
    key_stat: '98% AmLaw 100',
    founded: '2012',
    hq_location: 'Chicago, IL',
    employees: '800+',
    featured: 0,
  },
]

export const subdomains = [
  // Company subdomains
  { subdomain: 'harvey', type: 'company', status: 'claimed', owner_name: 'Harvey AI' },
  { subdomain: 'casetext', type: 'company', status: 'claimed', owner_name: 'Casetext' },
  { subdomain: 'ironclad', type: 'company', status: 'claimed', owner_name: 'Ironclad' },
  { subdomain: 'westlaw', type: 'company', status: 'available' },
  { subdomain: 'lexis', type: 'company', status: 'available' },
  { subdomain: 'everlaw', type: 'company', status: 'available' },
  // Agent identities
  { subdomain: 'research', type: 'agent', status: 'available', agent_name: 'Research Agent', agent_description: 'Legal research AI' },
  { subdomain: 'contract', type: 'agent', status: 'available', agent_name: 'Contract Agent', agent_description: 'Contract analysis AI' },
  { subdomain: 'discovery', type: 'agent', status: 'available', agent_name: 'Discovery Agent', agent_description: 'eDiscovery AI' },
  { subdomain: 'compliance', type: 'agent', status: 'available', agent_name: 'Compliance Agent', agent_description: 'Regulatory compliance AI' },
  // Category subdomains
  { subdomain: 'litigation', type: 'category', status: 'available' },
  { subdomain: 'corporate', type: 'category', status: 'available' },
  { subdomain: 'ip', type: 'category', status: 'available' },
  { subdomain: 'employment', type: 'category', status: 'available' },
  { subdomain: 'api', type: 'reserved', status: 'reserved' },
]

export const articles = [
  {
    title: 'Harvey AI Raises $80M Series B for Legal AI',
    excerpt: 'OpenAI-backed legal AI startup expands into contract drafting and due diligence.',
    category: 'Funding',
    published_at: new Date().toISOString(),
  },
  {
    title: 'Thomson Reuters Acquires Casetext for $650M',
    excerpt: 'CoCounsel AI technology to be integrated across Westlaw platform.',
    category: 'M&A',
    published_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    title: 'AI Now Drafts 30% of Standard Legal Documents',
    excerpt: 'Survey shows rapid adoption of AI drafting tools among corporate legal departments.',
    category: 'Research',
    published_at: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    title: 'ABA Issues Guidelines for Lawyer AI Use',
    excerpt: 'New ethical guidance clarifies responsibilities when using AI legal tools.',
    category: 'Policy',
    published_at: new Date(Date.now() - 259200000).toISOString(),
  },
]

export const outbound = [
  { company: 'Harvey AI', contact_name: 'Winston Weinberg', title: 'CEO', priority: 'high', status: 'sent' },
  { company: 'Ironclad', contact_name: 'Jason Boehmig', title: 'CEO', priority: 'high', status: 'sent' },
  { company: 'Thomson Reuters', contact_name: 'Steve Hasker', title: 'CEO', priority: 'high', status: 'sent' },
  { company: 'Everlaw', contact_name: 'AJ Shankar', title: 'CEO', priority: 'medium', status: 'sent' },
]
