// Defense vertical seed data (e.g., military.ai)
export const companies = [
  // Disruptors
  {
    company_name: 'Anduril Industries',
    slug: 'anduril',
    description: 'Defense technology company building autonomous systems and AI-powered defense capabilities. Founded by Palmer Luckey.',
    website: 'https://anduril.com',
    categories: JSON.stringify(['Autonomous Systems', 'AI/ML', 'Counter-UAS']),
    company_type: 'disruptor',
    key_stat: '$14B Valuation',
    founded: '2017',
    hq_location: 'Costa Mesa, CA',
    employees: '2500+',
    featured: 1,
  },
  {
    company_name: 'Palantir Technologies',
    slug: 'palantir',
    description: 'Data analytics and AI platform for defense and intelligence. Powers military decision-making with real-time data fusion.',
    website: 'https://palantir.com',
    categories: JSON.stringify(['AI/ML', 'Command & Control', 'Cybersecurity']),
    company_type: 'disruptor',
    key_stat: '$70B Market Cap',
    founded: '2003',
    hq_location: 'Denver, CO',
    employees: '3500+',
    featured: 1,
  },
  {
    company_name: 'Shield AI',
    slug: 'shield-ai',
    description: 'Building the world\'s best AI pilot. Autonomous drones and aircraft for defense applications.',
    website: 'https://shield.ai',
    categories: JSON.stringify(['Autonomous Systems', 'AI/ML', 'Robotics']),
    company_type: 'disruptor',
    key_stat: '$2.7B Valuation',
    founded: '2015',
    hq_location: 'San Diego, CA',
    employees: '800+',
    featured: 1,
  },
  {
    company_name: 'Rebellion Defense',
    slug: 'rebellion',
    description: 'Software company building AI-powered simulation and decision support systems for national security.',
    website: 'https://rebelliondefense.com',
    categories: JSON.stringify(['AI/ML', 'Command & Control']),
    company_type: 'disruptor',
    key_stat: '$1B Valuation',
    founded: '2019',
    hq_location: 'Washington, DC',
    employees: '400+',
    featured: 0,
  },
  {
    company_name: 'Helsing',
    slug: 'helsing',
    description: 'European defense AI company building battlefield AI systems. Strong NATO partnerships.',
    website: 'https://helsing.ai',
    categories: JSON.stringify(['AI/ML', 'Electronic Warfare']),
    company_type: 'disruptor',
    key_stat: '$5B Valuation',
    founded: '2021',
    hq_location: 'Munich, Germany',
    employees: '400+',
    featured: 0,
  },
  // Legacy Primes
  {
    company_name: 'Lockheed Martin',
    slug: 'lockheed',
    description: 'World\'s largest defense contractor. F-35, missile defense, space systems, AI integration across platforms.',
    website: 'https://lockheedmartin.com',
    categories: JSON.stringify(['Autonomous Systems', 'Space', 'AI/ML']),
    company_type: 'legacy',
    key_stat: '$67B Revenue',
    founded: '1995',
    hq_location: 'Bethesda, MD',
    employees: '116000+',
    featured: 1,
  },
  {
    company_name: 'Northrop Grumman',
    slug: 'northrop',
    description: 'Global aerospace and defense. B-21 Raider, autonomous systems, space and cyber capabilities.',
    website: 'https://northropgrumman.com',
    categories: JSON.stringify(['Autonomous Systems', 'Space', 'Cybersecurity']),
    company_type: 'legacy',
    key_stat: '$39B Revenue',
    founded: '1994',
    hq_location: 'Falls Church, VA',
    employees: '95000+',
    featured: 0,
  },
  {
    company_name: 'RTX (Raytheon)',
    slug: 'rtx',
    description: 'Merged Raytheon and UTC. Missiles, radar, cyber, and integrated defense systems.',
    website: 'https://rtx.com',
    categories: JSON.stringify(['Electronic Warfare', 'Cybersecurity', 'AI/ML']),
    company_type: 'legacy',
    key_stat: '$69B Revenue',
    founded: '2020',
    hq_location: 'Arlington, VA',
    employees: '180000+',
    featured: 0,
  },
  {
    company_name: 'General Dynamics',
    slug: 'general-dynamics',
    description: 'Combat vehicles, submarines, IT services. Major programs across land, sea, and cyber domains.',
    website: 'https://gd.com',
    categories: JSON.stringify(['Command & Control', 'Cybersecurity']),
    company_type: 'legacy',
    key_stat: '$42B Revenue',
    founded: '1952',
    hq_location: 'Reston, VA',
    employees: '100000+',
    featured: 0,
  },
  {
    company_name: 'L3Harris Technologies',
    slug: 'l3harris',
    description: 'Communications, electronic warfare, ISR. Major supplier of defense electronics and systems integration.',
    website: 'https://l3harris.com',
    categories: JSON.stringify(['Electronic Warfare', 'Command & Control', 'Space']),
    company_type: 'legacy',
    key_stat: '$18B Revenue',
    founded: '2019',
    hq_location: 'Melbourne, FL',
    employees: '50000+',
    featured: 0,
  },
  {
    company_name: 'BAE Systems',
    slug: 'bae',
    description: 'UK-headquartered global defense. Combat vehicles, naval ships, electronic systems, cyber.',
    website: 'https://baesystems.com',
    categories: JSON.stringify(['Electronic Warfare', 'Cybersecurity']),
    company_type: 'legacy',
    key_stat: '$25B Revenue',
    founded: '1999',
    hq_location: 'London, UK',
    employees: '90000+',
    featured: 0,
  },
  {
    company_name: 'Boeing Defense',
    slug: 'boeing',
    description: 'Defense, Space & Security division. Fighter jets, satellites, autonomous systems, MQ-25 tanker drone.',
    website: 'https://boeing.com/defense',
    categories: JSON.stringify(['Autonomous Systems', 'Space']),
    company_type: 'legacy',
    key_stat: '$23B Revenue',
    founded: '1916',
    hq_location: 'Arlington, VA',
    employees: '140000+',
    featured: 0,
  },
]

export const subdomains = [
  // Company subdomains
  { subdomain: 'anduril', type: 'company', status: 'claimed', owner_name: 'Anduril Industries' },
  { subdomain: 'palantir', type: 'company', status: 'claimed', owner_name: 'Palantir Technologies' },
  { subdomain: 'shield-ai', type: 'company', status: 'claimed', owner_name: 'Shield AI' },
  { subdomain: 'lockheed', type: 'company', status: 'available' },
  { subdomain: 'northrop', type: 'company', status: 'available' },
  { subdomain: 'boeing', type: 'company', status: 'available' },
  { subdomain: 'raytheon', type: 'company', status: 'available' },
  { subdomain: 'bae', type: 'company', status: 'available' },
  { subdomain: 'l3harris', type: 'company', status: 'available' },
  { subdomain: 'gd', type: 'company', status: 'available' },
  // Agent identities
  { subdomain: 'lattice', type: 'agent', status: 'claimed', agent_name: 'Lattice', agent_description: 'Anduril command & control AI', owner_name: 'Anduril Industries' },
  { subdomain: 'aip', type: 'agent', status: 'claimed', agent_name: 'AIP', agent_description: 'Palantir Artificial Intelligence Platform', owner_name: 'Palantir Technologies' },
  { subdomain: 'hivemind', type: 'agent', status: 'claimed', agent_name: 'Hivemind', agent_description: 'Shield AI autonomous pilot', owner_name: 'Shield AI' },
  { subdomain: 'maven', type: 'agent', status: 'available', agent_name: 'Maven', agent_description: 'DoD Project Maven AI' },
  { subdomain: 'api', type: 'reserved', status: 'reserved' },
  { subdomain: 'docs', type: 'reserved', status: 'reserved' },
]

export const articles = [
  {
    title: 'Anduril Wins $1B Army Counter-UAS Contract',
    excerpt: 'Pentagon selects Anduril\'s Pulsar system for base defense across all service branches.',
    category: 'Contracts',
    published_at: new Date().toISOString(),
  },
  {
    title: 'Palantir AIP Deployed to 100+ Military Units',
    excerpt: 'AI decision platform now operational across Army, Navy, and Air Force commands.',
    category: 'Technology',
    published_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    title: 'Shield AI Raises $500M Series F at $2.7B Valuation',
    excerpt: 'Autonomous drone company expands production capacity and international partnerships.',
    category: 'Funding',
    published_at: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    title: 'Lockheed Martin Integrates AI Copilot into F-35',
    excerpt: 'Next-gen fighter gets autonomous wingman coordination and threat assessment.',
    category: 'Technology',
    published_at: new Date(Date.now() - 259200000).toISOString(),
  },
  {
    title: 'DoD Budget Allocates $15B for AI Modernization',
    excerpt: 'Largest AI investment in defense history targets autonomous systems and decision support.',
    category: 'Policy',
    published_at: new Date(Date.now() - 345600000).toISOString(),
  },
]

export const outbound = [
  { company: 'Anduril Industries', contact_name: 'Palmer Luckey', title: 'Founder', priority: 'high', status: 'sent' },
  { company: 'Shield AI', contact_name: 'Brandon Tseng', title: 'CEO', priority: 'high', status: 'sent' },
  { company: 'Lockheed Martin', contact_name: 'James Taiclet', title: 'CEO', priority: 'medium', status: 'sent' },
  { company: 'Northrop Grumman', contact_name: 'Kathy Warden', title: 'CEO', priority: 'medium', status: 'sent' },
  { company: 'Palantir Technologies', contact_name: 'Alex Karp', title: 'CEO', priority: 'high', status: 'sent' },
]
