// Tech vertical seed data (e.g., developer.ai, software.ai)
export const companies = [
  {
    company_name: 'GitHub Copilot',
    slug: 'github-copilot',
    description: 'AI pair programmer. Code completion and generation powered by OpenAI Codex.',
    website: 'https://github.com/features/copilot',
    categories: JSON.stringify(['Dev Tools', 'AI/ML']),
    company_type: 'platform',
    key_stat: '28M+ Users',
    founded: '2021',
    hq_location: 'San Francisco, CA',
    employees: '—',
    featured: 1,
  },
  {
    company_name: 'Cursor',
    slug: 'cursor',
    description: 'AI-first code editor. Built for pair programming with AI.',
    website: 'https://cursor.sh',
    categories: JSON.stringify(['Dev Tools', 'AI/ML']),
    company_type: 'startup',
    key_stat: '500K+ Users',
    founded: '2022',
    hq_location: 'San Francisco, CA',
    employees: '50+',
    featured: 1,
  },
  {
    company_name: 'Vercel',
    slug: 'vercel',
    description: 'Frontend cloud platform. Deploy web apps with zero configuration.',
    website: 'https://vercel.com',
    categories: JSON.stringify(['Cloud Infrastructure', 'Dev Tools']),
    company_type: 'platform',
    key_stat: '$3.2B Valuation',
    founded: '2015',
    hq_location: 'San Francisco, CA',
    employees: '500+',
    featured: 1,
  },
  {
    company_name: 'Supabase',
    slug: 'supabase',
    description: 'Open source Firebase alternative. Postgres database with instant APIs.',
    website: 'https://supabase.com',
    categories: JSON.stringify(['Databases', 'APIs']),
    company_type: 'startup',
    key_stat: '1M+ Developers',
    founded: '2020',
    hq_location: 'San Francisco, CA',
    employees: '200+',
    featured: 0,
  },
  {
    company_name: 'Datadog',
    slug: 'datadog',
    description: 'Cloud monitoring and security platform. Observability at scale.',
    website: 'https://datadoghq.com',
    categories: JSON.stringify(['Observability', 'Security']),
    company_type: 'enterprise',
    key_stat: '$40B Market Cap',
    founded: '2010',
    hq_location: 'New York, NY',
    employees: '5000+',
    featured: 0,
  },
  {
    company_name: 'Stripe',
    slug: 'stripe',
    description: 'Payment infrastructure for the internet. APIs for any business model.',
    website: 'https://stripe.com',
    categories: JSON.stringify(['APIs', 'Dev Tools']),
    company_type: 'platform',
    key_stat: '$50B Valuation',
    founded: '2010',
    hq_location: 'San Francisco, CA',
    employees: '8000+',
    featured: 0,
  },
]

export const subdomains = [
  { subdomain: 'copilot', type: 'company', status: 'claimed', owner_name: 'GitHub' },
  { subdomain: 'cursor', type: 'company', status: 'claimed', owner_name: 'Cursor' },
  { subdomain: 'vercel', type: 'company', status: 'available' },
  { subdomain: 'supabase', type: 'company', status: 'available' },
  { subdomain: 'stripe', type: 'company', status: 'available' },
  { subdomain: 'code', type: 'agent', status: 'available', agent_name: 'Code Agent', agent_description: 'Code generation AI' },
  { subdomain: 'review', type: 'agent', status: 'available', agent_name: 'Review Agent', agent_description: 'Code review AI' },
  { subdomain: 'api', type: 'reserved', status: 'reserved' },
  { subdomain: 'docs', type: 'reserved', status: 'reserved' },
]

export const articles = [
  {
    title: 'GitHub Copilot Reaches 28 Million Users',
    excerpt: 'AI code assistant adoption accelerates as productivity gains become clear.',
    category: 'Product',
    published_at: new Date().toISOString(),
  },
  {
    title: 'Cursor Raises $60M for AI-First IDE',
    excerpt: 'Editor built around AI pair programming sees rapid developer adoption.',
    category: 'Funding',
    published_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    title: 'Stack Overflow Survey: 70% of Devs Using AI Tools',
    excerpt: 'Annual survey shows mainstream adoption of AI coding assistants.',
    category: 'Research',
    published_at: new Date(Date.now() - 172800000).toISOString(),
  },
]

export const outbound = [
  { company: 'GitHub', contact_name: 'Thomas Dohmke', title: 'CEO', priority: 'high', status: 'sent' },
  { company: 'Cursor', contact_name: 'Michael Truell', title: 'CEO', priority: 'high', status: 'sent' },
  { company: 'Vercel', contact_name: 'Guillermo Rauch', title: 'CEO', priority: 'medium', status: 'sent' },
]
